spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/public
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          # 認可サーバーのエンドポイントを設定
          issuer-uri: http://keycloak:8080/realms/myrealm

server:
  port: 8081

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG

messagestream:
  cors:
    # CORS 設定を application.yaml で外部化
    allowed-origin-patterns:
      - "*"
    allowed-methods:
      - "*"
    allowed-headers:
      - "*"
    allow-credentials: true
    mapping-path: "/**"

